services:
  app:
    image: santiagoaj/node_start:latest # Imagen de la aplicación creada por CI/CD
    ports: # Mapeo de puertos de la máquina host al contenedor
      - "4000:4000"
    restart: unless-stopped # Reinicia si falla

  prometheus:
    image: prom/prometheus:v3.2.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.size=1GB"  # Máximo 1GB de datos
      - "--storage.tsdb.retention.time=7d"  # Solo guarda datos de los últimos 7 días
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:11.5.2
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus

volumes: # Definición de volúmenes
  prometheus_data:
  grafana_data:
