services:
  app:
    build: # Construcción de la imagen
      context: . 
      dockerfile: Dockerfile.development # Archivo de configuración de la imagen
    ports: # Mapeo de puertos de la máquina host al contenedor
      - "4000:4000"
    depends_on:
      - mongo
    volumes:
      - ./logs:/app/logs  # Mapeo de logs
      - .:/app  # Ajustado para coincidir con WORKDIR /app del Dockerfile para hot reloading
      - /app/node_modules  # Evita sobrescribir node_modules con el volumen

  mongo:
    image: mongo:8.0.5
    ports:
      - "27017:27017"
    volumes: # Mapeo de volúmenes
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:1.0.2-18
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongo

  prometheus:
    image: prom/prometheus:v3.2.1
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.size=1GB"  # Máximo 1GB de datos
      - "--storage.tsdb.retention.time=7d"  # Solo guarda datos de los últimos 7 días
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:11.5.2
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning  # Montar provisioning de dashboards y data sources
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus

  loki:
    image: grafana/loki:3.4.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yml
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yml
      - loki_data:/loki

  promtail:
    image: grafana/promtail:3.4.2
    volumes:
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
      - ./logs:/logs # Monta el directorio donde están tus logs
    command: -config.file=/etc/promtail/promtail-config.yml

volumes: # Definición de volúmenes
  mongo_data:
  prometheus_data:
  grafana_data:
  loki_data:
