server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: local-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: nodejs
          __path__: /logs/errors*.log # Apunta al archivo de logs
    pipeline_stages:
      - json:
          expressions:
            path: path  # Extrae el campo "path" del JSON
      - labels:
          path:      # Convierte "path" en una label