name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          echo "PORT=${{ secrets.PORT }}" > .env.staging
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env.staging
          echo "MONGO_URL=${{ secrets.MONGO_URL }}" >> .env.staging

      - name: Loguearse en Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construir la imagen Docker
        run: |
          docker build -f Dockerfile.staging -t santiagoaj/node_start:latest .

      - name: Subir la imagen al registro
        run: |
          docker push santiagoaj/node_start:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Create .env file
        run: |
          echo "GRAFANA_ADMIN_USER=${{ secrets.STAGING_GRAFANA_ADMIN_USER }}" > .env
          echo "GRAFANA_ADMIN_PASSWORD=${{ secrets.STAGING_GRAFANA_ADMIN_PASSWORD }}" >> .env

      - name: Copiar .env al servidor
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.STAGING_SERVER_IP }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
          source: ".env"
          target: "/ruta/donde/esta/docker-compose"

      - name: Copiar docker-compose al servidor
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.STAGING_SERVER_IP }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
          source: "docker-compose.staging.yml"
          target: "/ruta/donde/esta/docker-compose"

      - name: Conectarse al servidor y actualizar contenedores
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_SERVER_IP }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
          script: |
            cd /ruta/donde/esta/docker-compose
            docker pull santiagoaj/node_start:latest
            docker-compose -f docker-compose.staging.yml down
            docker-compose -f docker-compose.staging.yml up -d
            docker image prune -f  # Elimina imágenes antiguas