name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Loguearse en Docker Hub (o GitHub Container Registry)
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construir la imagen Docker
        run: |
          docker build -f Dockerfile.staging -t santiagoaj/node_start:latest .

      - name: Subir la imagen al registro
        run: |
          docker push santiagoaj/node_start:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Copiar docker-compose al servidor
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.STAGING_SERVER_IP }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.staging.yml"
          target: "/ruta/donde/esta/docker-compose"

      - name: Conectarse al servidor y actualizar contenedores
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_SERVER_IP }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /ruta/donde/esta/docker-compose
            docker pull usuario/app-staging:latest
            docker-compose -f docker-compose.staging.yml down
            docker-compose -f docker-compose.staging.yml up -d
            docker image prune -f  # Elimina imágenes antiguas